#include "RetroEngine.hpp"

#include "ps3/MenuBG.cpp"
#include "ps3/TextLabel.cpp"
#include "ps3/PushButton.cpp"
#include "ps3/SubMenuButton.cpp"
#include "ps3/DialogPanel.cpp"
#include "ps3/FadeScreen.cpp"
#include "ps3/VirtualDPad.cpp"
#include "ps3/VirtualDPadM.cpp"
#include "ps3/SettingsScreen.cpp"
#include "ps3/RetroGameLoop.cpp"
#include "ps3/PauseMenu.cpp"
#include "ps3/SegaSplash.cpp"
#include "ps3/CWSplash.cpp"
#include "ps3/TitleScreen.cpp"
#include "ps3/StartGameButton.cpp"
#include "ps3/TimeAttackButton.cpp"
#include "ps3/AchievementsButton.cpp"
#include "ps3/MultiplayerButton.cpp"
#include "ps3/LeaderboardsButton.cpp"
#if RETRO_USE_MOD_LOADER
#include "ps3/ModsButton.cpp"
#include "ps3/ModInfoButton.cpp"
#include "ps3/ModsMenu.cpp"
#endif
#include "ps3/OptionsButton.cpp"
#include "ps3/BackButton.cpp"
#include "ps3/SegaIDButton.cpp"
#include "ps3/MenuControl.cpp"
#include "ps3/SaveSelect.cpp"
#include "ps3/PlayerSelectScreen.cpp"
#include "ps3/ZoneButton.cpp"
#include "ps3/RecordsScreen.cpp"
#include "ps3/TimeAttack.cpp"
#if !RETRO_USE_ORIGINAL_CODE
#include "ps3/AchievementDisplay.cpp"
#include "ps3/AchievementsMenu.cpp"
#endif
#include "ps3/InstructionsScreen.cpp"
#include "ps3/AboutScreen.cpp"
#include "ps3/CreditText.cpp"
#include "ps3/StaffCredits.cpp"
#include "ps3/OptionsMenu.cpp"
#if RETRO_USE_NETWORKING
#include "ps3/MultiplayerHandler.cpp"
#include "ps3/MultiplayerScreen.cpp"
#endif