#include "RetroEngine.hpp"

#include "new/MenuBG.cpp"
#include "new/TextLabel.cpp"
#include "new/PushButton.cpp"
#include "new/SubMenuButton.cpp"
#include "new/DialogPanel.cpp"
#include "new/FadeScreen.cpp"
#include "new/VirtualDPad.cpp"
#include "new/VirtualDPadM.cpp"
#include "new/SettingsScreen.cpp"
#include "new/RetroGameLoop.cpp"
#include "new/PauseMenu.cpp"
#include "new/SegaSplash.cpp"
#include "new/CWSplash.cpp"
#include "new/TitleScreen.cpp"
#include "new/StartGameButton.cpp"
#include "new/TimeAttackButton.cpp"
#include "new/AchievementsButton.cpp"
#include "new/MultiplayerButton.cpp"
#include "new/LeaderboardsButton.cpp"
#if RETRO_USE_MOD_LOADER
#include "new/ModsButton.cpp"
#include "new/ModInfoButton.cpp"
#include "new/ModsMenu.cpp"
#endif
#include "new/OptionsButton.cpp"
#include "new/BackButton.cpp"
#include "new/SegaIDButton.cpp"
#include "new/MenuControl.cpp"
#include "new/SaveSelect.cpp"
#include "new/PlayerSelectScreen.cpp"
#include "new/ZoneButton.cpp"
#include "new/RecordsScreen.cpp"
#include "new/TimeAttack.cpp"
#if !RETRO_USE_ORIGINAL_CODE
#include "new/AchievementDisplay.cpp"
#include "new/AchievementsMenu.cpp"
#endif
#include "new/InstructionsScreen.cpp"
#include "new/AboutScreen.cpp"
#include "new/CreditText.cpp"
#include "new/StaffCredits.cpp"
#include "new/OptionsMenu.cpp"
#if RETRO_USE_NETWORKING
#include "new/MultiplayerHandler.cpp"
#include "new/MultiplayerScreen.cpp"
#endif